services:

  scheduler-database:
    image: postgres:17.5
    container_name: scheduler-database
    ports:
      - "${SCHEDULER_DATABASE_EXTERNAL_PORT}:5432"
    environment:
      - POSTGRES_DB=${SCHEDULER_DATABASE_NAME}
      - POSTGRES_USER=${SCHEDULER_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${SCHEDULER_DATABASE_PASSWORD}
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    networks:
      - backend

  scheduler-frontend:
    image: ghcr.io/juniors-at-work/scheduler-service-frontend-prod:latest
    container_name: scheduler-frontend
    ports:
      - "80:80"
    depends_on:
      scheduler-database:
        condition: service_healthy
    environment:
      - BACKEND_URL=http://host.docker.internal:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: "wget -T5 -qO- http://localhost:80/actuator/health | grep UP || exit 1"
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - frontend

networks:
  frontend:
  backend:
